/**
 * SVG icon catalog — the ONLY place where MDI icons enter the JS bundle.
 *
 * Why: the old `@mdi/font` icon FONT shipped every one of its ~7000 glyphs
 * (~395 KiB woff2, render-blocking) even though the app uses ~120 icons.
 * With `@mdi/js`, each icon is a tiny SVG path string and the bundler
 * tree-shakes everything that is not imported here.
 *
 * How to add an icon (junior-friendly, 2 steps):
 *   1. Import its path below: `mdi-map-marker` → `mdiMapMarker`.
 *   2. Add one line to the map: `'mdi-map-marker': mdiMapMarker,`.
 * Then use it in any template as usual: `<v-icon icon="mdi-map-marker" />`.
 * In dev mode, a missing icon logs a console warning (see plugins/vuetify.ts).
 *
 * BLOG CATEGORIES: category icons live in the database (blog_categories.icon)
 * and are picked from the admin panel. Any NEW category icon must also be
 * registered here (same 2 steps above), otherwise it renders as an empty
 * glyph on the public blog.
 */
import {
  mdiAccessPoint,
  mdiAccountGroupOutline,
  mdiAlertCircle,
  mdiArrowDown,
  mdiArrowLeft,
  mdiArrowRight,
  mdiArrowRightThin,
  mdiArrowTopRight,
  mdiArrowUp,
  mdiBank,
  mdiBankOutline,
  mdiBookshelf,
  mdiBugOutline,
  mdiBus,
  mdiBusStop,
  mdiCached,
  mdiCalendar,
  mdiCalendarClock,
  mdiCalendarMonthOutline,
  mdiCalendarOutline,
  mdiCastle,
  mdiCheck,
  mdiCheckboxBlankOutline,
  mdiCheckboxMarked,
  mdiCheckCircle,
  mdiCheckCircleOutline,
  mdiChevronDown,
  mdiChevronLeft,
  mdiChevronRight,
  mdiChevronUp,
  mdiChurch,
  mdiCircle,
  mdiCity,
  mdiCityVariantOutline,
  mdiClockAlertOutline,
  mdiClockOutline,
  mdiClose,
  mdiCloseCircle,
  mdiCloudAlertOutline,
  mdiCloudDownloadOutline,
  mdiCloudUpload,
  mdiCompassOutline,
  mdiContentCopy,
  mdiCrosshairs,
  mdiCrosshairsGps,
  mdiDeleteAlertOutline,
  mdiDeleteOutline,
  mdiDotsHorizontalCircleOutline,
  mdiDownload,
  mdiEmailOutline,
  mdiEye,
  mdiEyedropper,
  mdiEyeOff,
  mdiEyeOffOutline,
  mdiFileDocumentOutline,
  mdiFlowerOutline,
  mdiFolderPlusOutline,
  mdiHomeCityOutline,
  mdiHomeGroup,
  mdiHomeOutline,
  mdiInformation,
  mdiInformationOutline,
  mdiKeyboard,
  mdiLibraryOutline,
  mdiLightbulbOnOutline,
  mdiLogout,
  mdiMagnify,
  mdiMagnifyClose,
  mdiMapMarker,
  mdiMapMarkerOffOutline,
  mdiMapMarkerOutline,
  mdiMapMarkerPath,
  mdiMapMarkerPlusOutline,
  mdiMapMarkerRadius,
  mdiMapMarkerRadiusOutline,
  mdiMapOutline,
  mdiMapSearchOutline,
  mdiMenu,
  mdiMenuDown,
  mdiMenuRight,
  mdiMessageTextOutline,
  mdiMinus,
  mdiMinusBox,
  mdiMoonWaningCrescent,
  mdiNavigation,
  mdiOpenInNew,
  mdiPageFirst,
  mdiPageLast,
  mdiPalette,
  mdiPaletteOutline,
  mdiPaperclip,
  mdiPencil,
  mdiPlay,
  mdiPlus,
  mdiPlusCircleOutline,
  mdiPostOutline,
  mdiRadioboxBlank,
  mdiRadioboxMarked,
  mdiRefresh,
  mdiScaleBalance,
  mdiShapeOutline,
  mdiShieldCheckOutline,
  mdiShieldLockOutline,
  mdiShuffleVariant,
  mdiSoccer,
  mdiSort,
  mdiStar,
  mdiStarFourPointsOutline,
  mdiStarHalfFull,
  mdiStarOffOutline,
  mdiStarOutline,
  mdiStarPlusOutline,
  mdiTextBoxSearchOutline,
  mdiTimetable,
  mdiTrain,
  mdiTrainCar,
  mdiTrainVariant,
  mdiTram,
  mdiTransitConnectionVariant,
  mdiTreeOutline,
  mdiTuneVariant,
  mdiUnfoldMoreHorizontal,
  mdiUpdate,
  mdiViewDashboardOutline,
  mdiWalk,
  mdiWeatherNight,
  mdiWheelchairAccessibility,
  mdiWhiteBalanceSunny,
  mdiWifiAlert,
  mdiWifiOff,
  mdiWifiSync,
} from '@mdi/js'

/**
 * kebab-case icon name (as written in templates) → SVG path.
 * Keys stay identical to the old font class names so NO template changes
 * were needed anywhere in the app.
 */
export const mdiIconPaths: Record<string, string> = {
  // ── Icons used in app templates and data (blog articles, composables) ──
  'mdi-access-point': mdiAccessPoint,
  'mdi-account-group-outline': mdiAccountGroupOutline,
  'mdi-arrow-down': mdiArrowDown,
  'mdi-arrow-left': mdiArrowLeft,
  'mdi-arrow-right': mdiArrowRight,
  'mdi-arrow-right-thin': mdiArrowRightThin,
  'mdi-arrow-top-right': mdiArrowTopRight,
  'mdi-bank': mdiBank,
  'mdi-bank-outline': mdiBankOutline,
  'mdi-bookshelf': mdiBookshelf,
  'mdi-bug-outline': mdiBugOutline,
  'mdi-bus': mdiBus,
  'mdi-bus-stop': mdiBusStop,
  'mdi-calendar-clock': mdiCalendarClock,
  'mdi-calendar-month-outline': mdiCalendarMonthOutline,
  'mdi-calendar-outline': mdiCalendarOutline,
  'mdi-castle': mdiCastle,
  'mdi-check': mdiCheck,
  'mdi-check-circle-outline': mdiCheckCircleOutline,
  'mdi-chevron-down': mdiChevronDown,
  'mdi-chevron-right': mdiChevronRight,
  'mdi-chevron-up': mdiChevronUp,
  'mdi-church': mdiChurch,
  'mdi-city': mdiCity,
  'mdi-city-variant-outline': mdiCityVariantOutline,
  'mdi-clock-alert-outline': mdiClockAlertOutline,
  'mdi-clock-outline': mdiClockOutline,
  'mdi-close': mdiClose,
  'mdi-cloud-alert-outline': mdiCloudAlertOutline,
  'mdi-cloud-download-outline': mdiCloudDownloadOutline,
  'mdi-compass-outline': mdiCompassOutline,
  'mdi-content-copy': mdiContentCopy,
  'mdi-crosshairs': mdiCrosshairs,
  'mdi-crosshairs-gps': mdiCrosshairsGps,
  'mdi-delete-alert-outline': mdiDeleteAlertOutline,
  'mdi-delete-outline': mdiDeleteOutline,
  'mdi-dots-horizontal-circle-outline': mdiDotsHorizontalCircleOutline,
  'mdi-download': mdiDownload,
  'mdi-email-outline': mdiEmailOutline,
  'mdi-eye': mdiEye,
  'mdi-eye-off': mdiEyeOff,
  'mdi-eye-off-outline': mdiEyeOffOutline,
  'mdi-file-document-outline': mdiFileDocumentOutline,
  'mdi-flower-outline': mdiFlowerOutline,
  'mdi-folder-plus-outline': mdiFolderPlusOutline,
  'mdi-home-city-outline': mdiHomeCityOutline,
  'mdi-home-group': mdiHomeGroup,
  'mdi-home-outline': mdiHomeOutline,
  'mdi-information-outline': mdiInformationOutline,
  'mdi-keyboard': mdiKeyboard,
  'mdi-library-outline': mdiLibraryOutline,
  'mdi-lightbulb-on-outline': mdiLightbulbOnOutline,
  'mdi-logout': mdiLogout,
  'mdi-magnify': mdiMagnify,
  'mdi-magnify-close': mdiMagnifyClose,
  'mdi-map-marker': mdiMapMarker,
  'mdi-map-marker-off-outline': mdiMapMarkerOffOutline,
  'mdi-map-marker-outline': mdiMapMarkerOutline,
  'mdi-map-marker-path': mdiMapMarkerPath,
  'mdi-map-marker-plus-outline': mdiMapMarkerPlusOutline,
  'mdi-map-marker-radius': mdiMapMarkerRadius,
  'mdi-map-marker-radius-outline': mdiMapMarkerRadiusOutline,
  'mdi-map-outline': mdiMapOutline,
  'mdi-map-search-outline': mdiMapSearchOutline,
  'mdi-menu': mdiMenu,
  'mdi-message-text-outline': mdiMessageTextOutline,
  'mdi-moon-waning-crescent': mdiMoonWaningCrescent,
  'mdi-navigation': mdiNavigation,
  'mdi-open-in-new': mdiOpenInNew,
  'mdi-palette-outline': mdiPaletteOutline,
  'mdi-play': mdiPlay,
  'mdi-plus': mdiPlus,
  'mdi-plus-circle-outline': mdiPlusCircleOutline,
  'mdi-post-outline': mdiPostOutline,
  'mdi-refresh': mdiRefresh,
  'mdi-scale-balance': mdiScaleBalance,
  'mdi-shape-outline': mdiShapeOutline,
  'mdi-shield-check-outline': mdiShieldCheckOutline,
  'mdi-shield-lock-outline': mdiShieldLockOutline,
  'mdi-shuffle-variant': mdiShuffleVariant,
  'mdi-soccer': mdiSoccer,
  'mdi-sort': mdiSort,
  'mdi-star': mdiStar,
  'mdi-star-four-points-outline': mdiStarFourPointsOutline,
  'mdi-star-off-outline': mdiStarOffOutline,
  'mdi-star-outline': mdiStarOutline,
  'mdi-star-plus-outline': mdiStarPlusOutline,
  'mdi-text-box-search-outline': mdiTextBoxSearchOutline,
  'mdi-timetable': mdiTimetable,
  'mdi-train': mdiTrain,
  'mdi-train-car': mdiTrainCar,
  'mdi-train-variant': mdiTrainVariant,
  'mdi-tram': mdiTram,
  'mdi-transit-connection-variant': mdiTransitConnectionVariant,
  'mdi-tree-outline': mdiTreeOutline,
  'mdi-tune-variant': mdiTuneVariant,
  'mdi-update': mdiUpdate,
  'mdi-view-dashboard-outline': mdiViewDashboardOutline,
  'mdi-walk': mdiWalk,
  'mdi-weather-night': mdiWeatherNight,
  'mdi-wheelchair-accessibility': mdiWheelchairAccessibility,
  'mdi-white-balance-sunny': mdiWhiteBalanceSunny,
  'mdi-wifi-alert': mdiWifiAlert,
  'mdi-wifi-off': mdiWifiOff,
  'mdi-wifi-sync': mdiWifiSync,

  // ── Names used in templates that do NOT exist in MDI ──
  // The old font silently rendered an empty glyph for these. We map them
  // to the closest real icon instead (the "off" state is already conveyed
  // by the dimmed color in LineFilterChips.vue).
  'mdi-bus-off': mdiBus,
  'mdi-train-variant-off': mdiTrainVariant,

  // ── Icons required by Vuetify's internal $aliases ──
  // (v-alert types, v-select dropdown, v-checkbox, v-pagination, clearable
  // fields, v-expansion-panel chevrons…). Do not remove.
  'mdi-alert-circle': mdiAlertCircle,
  'mdi-arrow-up': mdiArrowUp,
  'mdi-cached': mdiCached,
  'mdi-calendar': mdiCalendar,
  'mdi-check-circle': mdiCheckCircle,
  'mdi-checkbox-blank-outline': mdiCheckboxBlankOutline,
  'mdi-checkbox-marked': mdiCheckboxMarked,
  'mdi-chevron-left': mdiChevronLeft,
  'mdi-circle': mdiCircle,
  'mdi-close-circle': mdiCloseCircle,
  'mdi-cloud-upload': mdiCloudUpload,
  'mdi-eyedropper': mdiEyedropper,
  'mdi-information': mdiInformation,
  'mdi-menu-down': mdiMenuDown,
  'mdi-menu-right': mdiMenuRight,
  'mdi-minus': mdiMinus,
  'mdi-minus-box': mdiMinusBox,
  'mdi-page-first': mdiPageFirst,
  'mdi-page-last': mdiPageLast,
  'mdi-palette': mdiPalette,
  'mdi-paperclip': mdiPaperclip,
  'mdi-pencil': mdiPencil,
  'mdi-radiobox-blank': mdiRadioboxBlank,
  'mdi-radiobox-marked': mdiRadioboxMarked,
  'mdi-star-half-full': mdiStarHalfFull,
  'mdi-unfold-more-horizontal': mdiUnfoldMoreHorizontal,
}
